const CONFIG = Object.freeze({
    WIDTH: 900,
    HEIGHT: 600,
    COLORS: Object.freeze({
        BG_PRIMARY: '#0f0f2e',
        BG_SECONDARY: '#1a1a3e',
        BG_CARD: '#252550',
        ACCENT: '#6366f1',
        ACCENT_LIGHT: '#818cf8',
        SUCCESS: '#10b981',
        ERROR: '#ef4444',
        WARNING: '#f59e0b',
        TEXT_PRIMARY: '#f1f5f9',
        TEXT_SECONDARY: '#94a3b8',
        TEXT_MUTED: '#64748b',
        GOLD: '#fbbf24',
        SILVER: '#9ca3af',
        BRONZE: '#d97706',
        GLOW_ACCENT: 'rgba(99, 102, 241, 0.4)',
        GLOW_SUCCESS: 'rgba(16, 185, 129, 0.4)',
        GLOW_ERROR: 'rgba(239, 68, 68, 0.4)',
    }),
    FONTS: Object.freeze({
        TITLE: 'bold 42px "Segoe UI", sans-serif',
        SUBTITLE: '24px "Segoe UI", sans-serif',
        HEADING: 'bold 28px "Segoe UI", sans-serif',
        BODY: '18px "Segoe UI", sans-serif',
        BODY_BOLD: 'bold 18px "Segoe UI", sans-serif',
        SMALL: '14px "Segoe UI", sans-serif',
        BUTTON: 'bold 20px "Segoe UI", sans-serif',
        INPUT: '22px "Segoe UI", sans-serif',
        SCORE: 'bold 64px "Segoe UI", sans-serif',
        EMOJI: '48px "Segoe UI Emoji", "Noto Color Emoji", sans-serif',
        BADGE: 'bold 16px "Segoe UI", sans-serif',
    }),
    ANIM: Object.freeze({
        FEEDBACK_DURATION: 1800,
        PARTICLE_COUNT: 12,
        PARTICLE_LIFE: 60,
    }),
    SCREENS: Object.freeze({
        WELCOME: 'welcome',
        PLAYING: 'playing',
        FEEDBACK: 'feedback',
        RESULTS: 'results',
    }),
});
